'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'
import { AlertCircle, Check, CheckCircle2, Copy, ExternalLink, MessagesSquare as Facebook, Loader2, RefreshCw, ShieldCheck, Trash2 } from 'lucide-react'

type Channel = { page_id: string; page_name: string | null; status: string; connected_at: string | null; last_webhook_at: string | null; last_error: string | null }

export function AssistantFacebookTab({ assistantId }: { assistantId: string }) {
  const [channel, setChannel] = useState<Channel | null>(null); const [pageId, setPageId] = useState(''); const [token, setToken] = useState('')
  const [webhook, setWebhook] = useState('https://conversaai.store/api/webhooks/facebook'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [copied, setCopied] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/assistants/${assistantId}/facebook`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo cargar Facebook.'); setChannel(data.channel || null); setPageId(data.channel?.page_id || ''); setWebhook(data.webhookUrl || webhook) } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo cargar Facebook.') } finally { setLoading(false) } }, [assistantId, webhook])
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer) }, [load])
  const connect = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); try { const response = await fetch(`/api/assistants/${assistantId}/facebook`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pageId, pageAccessToken: token }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo conectar Facebook.'); setChannel(data.channel); setToken(''); setMessage(data.message) } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo conectar Facebook.') } finally { setSaving(false) } }
  const disconnect = async () => { if (!window.confirm('¿Desconectar esta página? El historial se conservará.')) return; setSaving(true); const response = await fetch(`/api/assistants/${assistantId}/facebook`, { method: 'DELETE' }); if (response.ok) { setChannel(null); setPageId(''); setMessage('Facebook Messenger fue desconectado.') } else setMessage('No se pudo desconectar Facebook.'); setSaving(false) }
  if (loading) return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-brand-violet" /></div>
  const connected = channel?.status === 'connected'
  return <div className="mx-auto max-w-5xl space-y-5">
    <section className="overflow-hidden rounded-3xl border border-card-border bg-card-bg shadow-sm">
      <div className="flex flex-col gap-4 border-b border-card-border p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#1877F2]/10 text-[#1877F2]"><Facebook className="h-6 w-6" /></span><div><div className="flex items-center gap-2"><h2 className="dashboard-strong text-xl font-bold">Facebook Messenger</h2><span className={`rounded-full border px-2 py-0.5 text-[11px] font-bold ${connected ? 'border-emerald-500/25 bg-emerald-500/10 text-emerald-500' : 'border-amber-500/25 bg-amber-500/10 text-amber-500'}`}>{connected ? 'CONECTADO' : 'PENDIENTE'}</span></div><p className="dashboard-muted mt-1 text-sm">Responde mensajes de tu Página desde el inbox de ConversaAI.</p></div></div><button onClick={() => void load()} className="dashboard-icon-button flex h-10 w-10 items-center justify-center rounded-xl border border-card-border" aria-label="Actualizar"><RefreshCw className="h-4 w-4" /></button></div>
      {connected && channel ? <div className="grid gap-5 p-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 text-emerald-500" /><div><strong className="dashboard-strong block">{channel.page_name || 'Página verificada por Meta'}</strong><span className="dashboard-muted text-sm">ID {channel.page_id}</span></div></div><div className="mt-5 rounded-xl border border-card-border bg-card-bg p-3"><small className="dashboard-muted block">Último webhook</small><strong className="dashboard-strong text-sm">{channel.last_webhook_at ? new Date(channel.last_webhook_at).toLocaleString('es') : 'Esperando primer mensaje'}</strong></div></div><div className="flex flex-col justify-between rounded-2xl border border-card-border p-5"><div><ShieldCheck className="mb-3 h-6 w-6 text-brand-violet" /><strong className="dashboard-strong block">Conexión protegida</strong><p className="dashboard-muted mt-1 text-sm">La firma de Meta se valida y el token cifrado nunca vuelve al navegador.</p></div><button onClick={() => void disconnect()} disabled={saving} className="mt-5 inline-flex items-center justify-center gap-2 rounded-xl border border-red-500/25 px-4 py-2.5 text-sm font-semibold text-red-500 hover:bg-red-500/5"><Trash2 className="h-4 w-4" /> Desconectar</button></div></div> :
      <form onSubmit={connect} className="grid gap-6 p-6 lg:grid-cols-[1fr_.9fr]"><div className="space-y-4"><div><label className="dashboard-strong mb-1.5 block text-sm font-semibold">ID de la Página de Facebook</label><input value={pageId} onChange={event => setPageId(event.target.value.replace(/\D/g, ''))} required inputMode="numeric" maxLength={30} placeholder="Ej. 123456789012345" className="dashboard-input w-full rounded-xl border-2 border-card-border bg-card-bg px-4 py-3 shadow-sm outline-none transition focus:border-brand-violet focus:ring-4 focus:ring-brand-violet/10" /></div><div><label className="dashboard-strong mb-1.5 block text-sm font-semibold">Token de acceso de la Página</label><input type="password" value={token} onChange={event => setToken(event.target.value)} required autoComplete="new-password" maxLength={4096} placeholder="Pega aquí el token permanente" className="dashboard-input w-full rounded-xl border-2 border-card-border bg-card-bg px-4 py-3 shadow-sm outline-none transition focus:border-brand-violet focus:ring-4 focus:ring-brand-violet/10" /><p className="dashboard-muted mt-1.5 text-xs">Se cifra con AES-256-GCM antes de guardarse.</p></div><button disabled={saving} className="gradient-btn inline-flex w-full items-center justify-center gap-2 rounded-xl px-5 py-3 font-semibold text-white disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />} Validar y conectar</button></div><div className="rounded-2xl border border-card-border bg-black/[0.025] p-5"><h3 className="dashboard-strong font-bold">Cuando termines tu Página</h3><ol className="dashboard-muted mt-4 space-y-3 text-sm"><li><strong className="dashboard-strong">1.</strong> Añádela a la aplicación de Meta.</li><li><strong className="dashboard-strong">2.</strong> Genera un token permanente con permisos mínimos.</li><li><strong className="dashboard-strong">3.</strong> Configura y verifica este webhook.</li></ol><div className="mt-5 rounded-xl border border-card-border bg-card-bg p-3"><small className="dashboard-muted block">URL del webhook</small><div className="mt-1 flex items-center gap-2"><code className="dashboard-strong min-w-0 flex-1 truncate text-xs">{webhook}</code><button type="button" onClick={async () => { await navigator.clipboard.writeText(webhook); setCopied(true); window.setTimeout(() => setCopied(false), 1800) }} className="p-1.5 text-brand-violet" aria-label="Copiar">{copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}</button></div></div><a href="https://developers.facebook.com/apps/" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1.5 text-sm font-semibold text-brand-cyan">Abrir Meta for Developers <ExternalLink className="h-3.5 w-3.5" /></a></div></form>}
      {message && <div className="mx-6 mb-6 flex items-start gap-2 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-sm text-amber-600"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />{message}</div>}
    </section>
  </div>
}
