revoke all on table public.assistants from anon;
revoke all on table public.assistant_channels from anon;
revoke all on table public.assistant_domains from anon;
revoke all on table public.assistant_test_messages from anon;
revoke all on table public.conversations from anon;
revoke all on table public.leads from anon;
revoke all on table public.messages from anon;
revoke all on table public.notifications from anon;
revoke all on table public.profiles from anon;
revoke all on table public.subscriptions from anon;
revoke all on table public.user_settings from anon;
revoke all on table public.audit_logs from anon;
revoke all on table public.billing_payments from anon;

revoke all on table public.assistants from authenticated;
grant select, insert, update, delete on table public.assistants to authenticated;
revoke all on table public.assistant_channels from authenticated;
grant select, insert, update, delete on table public.assistant_channels to authenticated;
revoke all on table public.assistant_domains from authenticated;
grant select on table public.assistant_domains to authenticated;
revoke all on table public.assistant_test_messages from authenticated;
grant select, insert, update, delete on table public.assistant_test_messages to authenticated;
revoke all on table public.conversations from authenticated;
grant select on table public.conversations to authenticated;
revoke all on table public.leads from authenticated;
grant select on table public.leads to authenticated;
revoke all on table public.messages from authenticated;
grant select on table public.messages to authenticated;
revoke all on table public.notifications from authenticated;
grant select, update on table public.notifications to authenticated;
revoke all on table public.profiles from authenticated;
grant select, update on table public.profiles to authenticated;
revoke all on table public.subscriptions from authenticated;
grant select on table public.subscriptions to authenticated;
revoke all on table public.user_settings from authenticated;
grant select on table public.user_settings to authenticated;
revoke all on table public.audit_logs from authenticated;
grant select on table public.audit_logs to authenticated;
revoke all on table public.billing_payments from authenticated;
grant select on table public.billing_payments to authenticated;
revoke all on table public.reviews from anon, authenticated;
grant select on table public.reviews to anon, authenticated;
grant insert, update, delete on table public.reviews to authenticated;
